# Generated by Django 3.2.5 on 2022-10-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=15)),
                ('floor', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'stuff',
            },
        ),
    ]
