# Generated by Django 3.2.5 on 2022-10-31 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('jobTitle', models.CharField(max_length=10)),
                ('serviceUnits', models.CharField(max_length=10)),
                ('emailAddr', models.EmailField(max_length=45)),
                ('permissions', models.CharField(choices=[('A', 'Administer'), ('R', 'RegionSupervisor'), ('N', 'Normal')], max_length=1)),
                ('activation', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Control_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.account')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.area')),
            ],
        ),
    ]
