# Generated by Django 3.2.5 on 2022-10-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_account_account_control_area'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='account_control_area',
            table='Account_Control_Area',
        ),
        migrations.AlterModelTable(
            name='area',
            table='Area',
        ),
    ]
