# Generated by Django 3.2.5 on 2022-11-02 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20221031_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=8)),
                ('connection', models.BooleanField(default=False)),
                ('current', models.DecimalField(decimal_places=2, max_digits=9)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=9)),
                ('power', models.DecimalField(decimal_places=2, max_digits=9)),
                ('KwH', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mode', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 39, 55, 380230))),
            ],
        ),
    ]
