# Generated by Django 3.2.5 on 2022-11-02 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_electricity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 40, 12, 870912)),
        ),
        migrations.AlterModelTable(
            name='electricity',
            table='Electricity',
        ),
    ]
