# Generated by Django 3.2.5 on 2022-11-02 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_auto_20221102_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 47, 38, 570794)),
        ),
    ]
