# Generated by Django 3.2.5 on 2022-11-08 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_alter_electricity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='KwH',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='power',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 12, 1, 16, 721037)),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='voltage',
            field=models.FloatField(),
        ),
    ]
