# Generated by Django 4.2.3 on 2023-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('permission', models.CharField(choices=[('A', '管理員'), ('R', '區域負責人'), ('N', '一般使用者')], max_length=1)),
                ('activation', models.BooleanField(choices=[(True, '啟用'), (False, '停用')], default=False)),
            ],
            options={
                'db_table': 'Stuff',
                'permissions': (('Admin', '管理人'), ('Region', '區域負責人'), ('Normal', '一般使用者')),
            },
        ),
    ]
